# configuration for https://travis-ci.org/PaycoinFoundation/paycoinj
sudo: false
language: java
jdk: oraclejdk8
install: true # remove default
script:
  - mvn -q clean install -Pno-network
  - jdk_switcher use openjdk6
  - cd orchid
  - mvn -q clean package
  - cd ../core
  - mvn -q clean package -Pno-network
